services:
  web:
    container_name: dragonfable-web
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "40000:80"
    volumes:
      - ./src/cdn/:/var/www/html/cdn/
      - ./src/server-emulator/:/var/www/html/server-emulator/
      - ./src/web/:/var/www/html/web/
      - ./dev-tools/:/var/www/html/dev-tools/
