<?php

$base = __DIR__;

try {
    if(!canSetup()) {
        die(\json_encode([
            "success" => true,
            "message" => "The server is already setup. If you want to setup again, please delete the .config.php file or remove the environment variables. Nothing was changed."
        ]));
    }

    generateConfig();
    die(\json_encode([
        "success" => true,
        "message" => "The server is successfully setup. Now we will finish the setup by creating the database schema. This can take a few minutes, just wait please."
    ]));
} catch(\Exception $e) {
    die(\json_encode([
        "success" => false,
        "message" => $e->getMessage()
    ]));
}

function canSetup(): bool {
    global $base;
    try {
        include "includes/env-loader.php";

        // settings is ok, we can't setup again unless we delete the .config.php file or remove the environment variables
        return false;
    } catch (\Exception $e) {
        // settings is not ok, we can setup again
        return true;
    }
}

function getConfig(): array {
    global $base;

    $input = \json_decode(\file_get_contents('php://input'), true);
    if(!$input) {
        throw new \Exception("Invalid input.");
    }

    if(!isset($input["DB_DRIVER"])) {
        throw new \Exception("The DB_DRIVER is required.");
    }

    if(!isset($input["DB_OPTIONS"])) {
        throw new \Exception("The DB_OPTIONS is required.");
    }

    if($input["DB_DRIVER"] === "\hiperesp\server\storage\SQLite") {
        if(\trim($input["DB_OPTIONS"]["location"])==="") {
            $input["DB_OPTIONS"]["location"] = $base."/data/db.sqlite3";
        }
    }

    $config = [];
    $config["DB_DRIVER"] = $input["DB_DRIVER"];
    $config["DB_OPTIONS"] = \json_encode($input["DB_OPTIONS"]);

    return $config;
}

function generateConfig(): bool {
    global $base;
    $config = getConfig();

    $configStr = \var_export($config, true);
    \file_put_contents($base . "/.config.php", "<?php\n# This file is auto-generated by the setup.php script.\n\$config = {$configStr};");

    return true;
}